### ISSUE TITLE
Error from process$new 

### ISSUE THREAD

**Issue by alexwhan** [MangoTheCat/processx#26]
Getting an error when I try to run the process$new example:

process$new("sleep", "20")

Error in wait_for_file(pidfile3) : 
  File was not created in 10 secs:

Getting the same error on two different windows machines, haven't tested on other OS

**Comment by gaborcsardi** [comment]
The error message should be better, but I am afraid that there is no `sleep` command on windows, that's why this fails.

**Comment by alexwhan** [comment]
Yeah, sorry just realised that... but it's failing with ping too.

This is working:
shell("ping -n 6 127.0.0.1") 

This is not
process$new("ping -n 6 127.0.0.1")

**Comment by gaborcsardi** [comment]
This should be 
```r
process$new(commandline = "ping -n 6 127.0.0.1")
```

By default the first argument is the command without arguments.

**Comment by alexwhan** [comment]
Still getting the same error I'm afraid.

But here's what I don't understand - I'm coming across this from trying to run tests for shiny.

When I run in interactively I get an error. eg from the tests dir:

app <- shinytest::shinyapp$new("apps/081-widgets-gallery") 
gives Error in wait_for_file(pidfile3) : 
  File was not created in 10 secs:

But when I run I test the package, those tests complete successfully. Is it possible there is some kind of permissions issue that is different for interactive use?

**Comment by alexwhan** [comment]
I also checked and when I run a test suit including:
expect_error(processx::process$new(commandline = "ping -n 6 127.0.0.1"), NA)

it passes, but when I run that test in the console it fails with the same error

**Comment by gaborcsardi** [comment]
> app <- shinytest::shinyapp$new("apps/081-widgets-gallery")
> gives Error in wait_for_file(pidfile3) :
> File was not created in 10 secs:

Are you sure that you are in the right directory and `apps/081-widgets-gallery` exists?

**Comment by alexwhan** [comment]
Yes, but to remove any doubt, that test above (using process$new directly) is using ping, not shinytest, and it's causing the same issues

**Comment by gaborcsardi** [comment]
But anyway, if `processx::process$new(commandline = "ping -n 6 127.0.0.1")` fails in a fresh R session, using the latest `processx` from GitHub, then please send the output of `devtools::session_info()`, and also the output of 

```r
tempdir()
cat("test", tmp <- tempfile())
tmp
readLines(tmp)
```

Thanks!

**Comment by alexwhan** [comment]
From a clean session:
> processx::process$new(commandline = "ping -n 6 127.0.0.1")
Error in wait_for_file(pidfile3) : 
  File was not created in 10 secs: C:\Users\WHA022\AppData\Local\Temp\RtmpgpvynO\file344c187e2c763
> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  English_Australia.1252      
 tz       Australia/Sydney            
 date     2016-11-24                  

Packages ------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                               
 assertthat   0.1        2013-12-06 CRAN (R 3.3.2)                       
 crayon       1.3.2      2016-06-28 CRAN (R 3.3.2)                       
 debugme      1.0.1      2016-11-23 Github (gaborcsardi/debugme@ed7f9aa) 
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.2)                       
 digest       0.6.10     2016-08-02 CRAN (R 3.3.2)                       
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.2)                       
 processx     1.0.0.9000 2016-11-23 Github (MangoTheCat/processx@2947567)
 R6           2.2.0      2016-10-05 CRAN (R 3.3.2)                       
 rstudioapi   0.6        2016-06-27 CRAN (R 3.3.2)                       
 withr        1.0.2      2016-06-20 CRAN (R 3.3.2) 

And...

> tempdir()
[1] "C:\\Users\\WHA022\\AppData\\Local\\Temp\\RtmpgpvynO"
> cat("test",tmp <- tempfile())
test C:\Users\WHA022\AppData\Local\Temp\RtmpgpvynO\file344cbc34e0
> tmp
[1] "C:\\Users\\WHA022\\AppData\\Local\\Temp\\RtmpgpvynO\\file344cbc34e0"
> readLines(tmp)
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\WHA022\AppData\Local\Temp\RtmpgpvynO\file344cbc34e0': No such file or directory

Wasn't sure if the second line was meant to name a file arg, so in case:

> tempdir()
[1] "C:\\Users\\WHA022\\AppData\\Local\\Temp\\RtmpgpvynO"
> cat("test", file = tmp <- tempfile())
> tmp
[1] "C:\\Users\\WHA022\\AppData\\Local\\Temp\\RtmpgpvynO\\file344c637a74d3"
> readLines(tmp)
[1] "test"
Warning message:
In readLines(tmp) :
  incomplete final line found on 'C:\Users\WHA022\AppData\Local\Temp\RtmpgpvynO\file344c637a74d3'

**Comment by gaborcsardi** [comment]
YEs, sorry, I meant a `file` arg of course.

**Comment by alexwhan** [comment]
no worries - especially after my errors!!

**Comment by gaborcsardi** [comment]
Do you have `wmic` installed on your system? Most windows installs should have it I think, but just to be sure. Does the following work?

```r
shell("wmic process")
```

**Comment by gaborcsardi** [comment]
OK, I can reproduce this from RStudio....

**Comment by alexwhan** [comment]
Yes, I've just checked, shell("wmic process") works, and process$new works from Rgui, looks like RStudio specific...

**Comment by gaborcsardi** [comment]
Yeah, and what is even more strange is that my `system()` call works if `wait = TRUE`, but fails when `wait = FALSE`, but only from RStudio. Wow.

**Comment by gaborcsardi** [comment]
And `system2` and `shell` do exactly the same....

**Comment by alexwhan** [comment]
Ok glad it wasn't just me

**Comment by gaborcsardi** [comment]
OK, I think I fixed it, can you please try again?

**Comment by gaborcsardi** [comment]
@alexwhan Please try when you have time, and reopen if you still have problems. Thanks.

**Comment by alexwhan** [comment]
Yes, working nicely now - thanks for such a prompt fix!
